#!/bin/bash
#$ -N knn
#$ -l mem=2G
#$ -pe default 4
#$ -cwd
#$ -o /dev/null
#$ -e /dev/null
#$ -t 1-7400:1

export PATH="$HOME/miniconda/bin:$PATH"
rm /tmp/* -R -f 2> /dev/null

source activate tensorflow-CS

i=$(( $SGE_TASK_ID ))
end=$(( $SGE_TASK_ID + $SGE_TASK_STEPSIZE ))
while [ $i -lt $end ]; do
	python ltn_code/run_knn.py $1 $2 $i -q
	i=$(( $i + 1 ))
done

source deactivate tensorflow-CS

rm /tmp/* -R -f 2> /dev/null
