#!/bin/bash
#$ -N install_tf
#$ -l mem=3G
#$ -pe default 2

wget -q https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
bash Miniconda3-latest-Linux-x86_64.sh -b -p "$HOME/miniconda"
rm Miniconda3-latest-Linux-x86_64.sh

export PATH="$HOME/miniconda/bin:$PATH"

conda create -y -q --name tensorflow python=2

source activate tensorflow
conda install -y -q -c anaconda tensorflow-gpu=1.1.0
source deactivate tensorflow

cd $HOME/miniconda/pkgs
rm *.tar.bz2 -f 2> /dev/null
